SearchBar Update (Debounce, performance, UI improve)
yavuzyalcintas/AskAnonym pull request #28
Opened 2023-03-06 18:50 UTC by ahmetilhn

- Debounce control added
- Not result screen added
- Loader added
- Network performance improved (not multiple req)

2023-03-06 20:10 UTC, Ketcap requested changes
Minimum 1 karakter olmasi lazim 1 karakterli profil isimleri var uzerinden gecersen tekrar inceleyelim.

2023-03-06 20:32 UTC, ahmetilhn commented
val.length >= queryLimit olarak güncelledim. @Ketcap

2023-03-07 09:58 UTC, yavuzyalcintas commented
@ahmetilhn linter hatası alıyor build olurken, rica etsem düzeltebilir misin

2023-03-07 10:34 UTC, ahmetilhn commented
> @ahmetilhn linter hatası alıyor build olurken, rica etsem düzeltebilir misin
Akşam müsaitim. Siz hızlıca atabilir misiniz?

2023-03-07 13:08 UTC, ahmetilhn commented
Gönderdim fixi @yavuzyalcintas @Ketcap

2023-03-07 16:14 UTC, Ketcap commented
@yavuzyalcintas ben approveladim hersey okey gozukuyo deploymenti kontrol et skinti cikmiyosa mergeleyebilirsin, eline saglik @ahmetilhn

2023-03-07 17:53 UTC, yavuzyalcintas approved these changes

2023-03-07 17:53 UTC, merged